### ISSUE TITLE
Checklist for MVP

### ISSUE THREAD

**Issue by trixr4kdz** [VicFrolov/Markit#42]
#Since we are nearing the end of the semester, I've made a general checklist for what we need to get done before our beta presentation based on our meeting on 11/13/16: 
- [ ] New Post: [Web App](https://github.com/VicFrolov/Markit/issues/38), [Android](https://github.com/VicFrolov/Markit/issues/46), [iOS](https://github.com/VicFrolov/Markit/issues/45)
- [ ] Find: [Web App](https://github.com/VicFrolov/Markit/issues/37), [Android](https://github.com/VicFrolov/Markit/issues/47), [iOS](https://github.com/VicFrolov/Markit/issues/36)
- [ ] Login: [Web App](https://github.com/VicFrolov/Markit/issues/51), [Android](https://github.com/VicFrolov/Markit/issues/50), [iOS](https://github.com/VicFrolov/Markit/issues/39)
- [ ] Sign-up: [Web App](https://github.com/VicFrolov/Markit/issues/41), [Android](https://github.com/VicFrolov/Markit/issues/44), [iOS](https://github.com/VicFrolov/Markit/issues/43)
- [ ] Profile: [Web App](https://github.com/VicFrolov/Markit/issues/40), [Android](https://github.com/VicFrolov/Markit/issues/49), [iOS](https://github.com/VicFrolov/Markit/issues/48)
- [ ] Hubs: [Web App](https://github.com/VicFrolov/Markit/issues/52), [Android](https://github.com/VicFrolov/Markit/issues/53), [iOS](https://github.com/VicFrolov/Markit/issues/54)

Please check the links for each group. Once a bullet is done for all 3 platforms, we can check them off here.

**Comment by trixr4kdz** [comment]
Just a reminder that we do have an issue tracker so whatever you've done for your parts (no matter how small it is), you should write a comment on the issue that you're assigned. It's even more helpful to write about what you're struggling with so we have an idea of our progress.
